version: '3.7'

services:

  backend:
    build: 
      context: .
      dockerfile: src/dockerfiles/Dockerfile.backend
    ports:
      - "5000:5000"
    
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: codegard
    volumes:
      - ./mongo-data:/data/db
      # - ./src/mongoDB/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js ### -- !!!for initial data!!!!
    ports:
      - "27017:27017"
  zookeeper:
    image: zookeeper
    restart: always
    hostname: zoo
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo:2888:3888;2181


# volumes:
#   - ./mongo-data:/ 