version: '3.7'

services:

  backend1:
    build: ./src/backEnd
    ports:
       - '5000:5000'
  backend2:
    build: ./src/backEnd
    ports:
       - '5001:5000'
  backend3:
    build: ./src/backEnd
    ports:
       - '5002:5000'
  backend4:
    build: ./src/backEnd
    ports:
       - '5003:5000'  
   
  
  haproxy:
    build: ./src/LB
    ports:
       - '80:80'
       - '8404:8404'   
    depends_on:
      - backend1
      - backend2
      - backend3
      - backend4
      
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: codegard
    volumes:
      - ./mongo-data:/data/db
      # - ./src/mongoDB/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js ### -- !!!for initial data!!!!
  # volumes:
#   - ./mongo-data:/ 
    ports:
      - '27017:27017'
    depends_on:
      - haproxy
      
   





