version: '3.7'

services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: codegard
    volumes:
      - ./mongo-data:/data/db
      # - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js ### -- !!!for initial data!!!!
    ports:
      - "27017:27017"

# volumes:
#   - ./mongo-data:/ 